### ISSUE TITLE
Permission to relicense derivative.

### ISSUE THREAD

**Issue by VentGrey** [Qwart376/Blue-Coffee#2]
Hello, first of all, I gotta say thank you for your themes, they are a great starting point for users :) 

I opened this issue to ask for a relicense. I've used this theme as the base for another theme in LeftWM called "Epitaph", at first it was a small reskin, but now the theme has grown so much and doesn't share a single line of code with Blue-Coffee since almost everything got re-written.

I'm asking for permission to relicense this to comply with the original leftwm-community-themes license which is BSD-3-Clause. If that's okay with you please let me know :) if not I'll keep the same MIT license for the project.

Thank you for your time :)

**Comment by Qwart376** [comment]
Blue-Coffee is fork of Coffee from which I deleted like 300 lines of code and rewrote couple of things in order for more user friendliness. I don't know much about licensing so I set the same MIT license as the original.

You have my blessing to do whatever you want, the Coffee author is a chill guy and probably won't have any problems with it.
